Add missing return type (void) for PrintProtoDisplay
protodpy.c:49:1: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
PrintProtoDisplay (struct protoDisplay *pdpy)
^

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>