Add missing prototype for PrintSockAddr
protodpy.c:53:5: error: implicit declaration of function 'PrintSockAddr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    PrintSockAddr (pdpy->address, pdpy->addrlen);
    ^

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>