Protect against unlikely NULL pointer dereference in FormatChooserArgument
NetaddrPort should only return NULL if it wasn't compiled with
support for the address family in use, but checking to be sure
makes static analyzer complain less.

Error: Null pointer dereference (CWE 476)
   Read from null pointer port
        at line 219 of xdm/choose.c in function 'FormatChooserArgument'.
          Function NetaddrPort may return constant 'NULL' at line 77,
           called at line 216.
          Null pointer introduced at line 77 of xdm/netaddr.c in function
           'NetaddrPort'.
        at line 220 of xdm/choose.c in function 'FormatChooserArgument'.
          Function NetaddrPort may return constant 'NULL' at line 77,
           called at line 216.
          Null pointer introduced at line 77 of xdm/netaddr.c in function
           'NetaddrPort'.

[ This bug was found by the Parfait 1.4.0 bug checking tool.
  http://labs.oracle.com/pls/apex/f?p=labs:49:::::P49_PROJECT_ID:13 ]

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>