xdm: Add missing include of <arpa/inet.h> for inet_ntop
netaddr.c:226:2: error: implicit declaration of function 'inet_ntop' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        inet_ntop(a->sa_family, &((struct sockaddr_in6 *) a)->sin6_addr,
        ^

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>